// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.DataBase;

namespace WebApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190426140809_AddedEntity")]
    partial class AddedEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.DataBase.Model.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<string>("Email");

                    b.Property<string>("Nume");

                    b.Property<string>("Prenume");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("WebApi.DataBase.Model.Poza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CalePoza");

                    b.Property<Guid>("IdProdus");

                    b.Property<bool>("IsProduct");

                    b.HasKey("Id");

                    b.ToTable("Poza");
                });

            modelBuilder.Entity("WebApi.DataBase.Model.Produs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CaleFolder");

                    b.Property<string>("Categorie");

                    b.Property<string>("Culoare");

                    b.Property<string>("Descriere");

                    b.Property<string>("Marime");

                    b.Property<double>("Pret");

                    b.Property<double?>("PretRedus");

                    b.Property<string>("Titlu");

                    b.HasKey("Id");

                    b.ToTable("Produs");
                });
#pragma warning restore 612, 618
        }
    }
}
